import { Person, Alert, Relationship, MessageEvent, RiskScoreBreakdown } from './types'

export const mockPeople: Person[] = [
  {
    id: 'person_1',
    name: 'Alex M.',
    department: 'Engineering',
    managerId: 'person_4',
    slackUserId: 'U001',
    riskScore: 8.1,
    riskLevel: 'critical',
    signals: ['sentiment_drift', 'after_hours', 'channel_exclusion'],
    lastActivity: '2024-06-17T14:32:00Z',
  },
  {
    id: 'person_2',
    name: 'Jordan Chen',
    department: 'Product',
    managerId: 'person_5',
    slackUserId: 'U002',
    riskScore: 5.2,
    riskLevel: 'warning',
    signals: ['response_drop'],
    lastActivity: '2024-06-17T10:15:00Z',
  },
  {
    id: 'person_3',
    name: 'Morgan Lee',
    department: 'Design',
    managerId: 'person_6',
    slackUserId: 'U003',
    riskScore: 3.1,
    riskLevel: 'watch',
    signals: ['after_hours'],
    lastActivity: '2024-06-17T16:45:00Z',
  },
  {
    id: 'person_4',
    name: 'Sam Taylor',
    department: 'Engineering',
    managerId: null,
    slackUserId: 'U004',
    riskScore: 2.0,
    riskLevel: 'normal',
    signals: [],
    lastActivity: '2024-06-17T17:20:00Z',
  },
  {
    id: 'person_5',
    name: 'Casey Martinez',
    department: 'Product',
    managerId: null,
    slackUserId: 'U005',
    riskScore: 1.5,
    riskLevel: 'normal',
    signals: [],
    lastActivity: '2024-06-17T15:10:00Z',
  },
  {
    id: 'person_6',
    name: 'Riley Park',
    department: 'Design',
    managerId: null,
    slackUserId: 'U006',
    riskScore: 4.3,
    riskLevel: 'watch',
    signals: ['channel_exclusion'],
    lastActivity: '2024-06-17T14:00:00Z',
  },
  {
    id: 'person_7',
    name: 'Devon Wright',
    department: 'Marketing',
    managerId: null,
    slackUserId: 'U007',
    riskScore: 2.7,
    riskLevel: 'normal',
    signals: [],
    lastActivity: '2024-06-17T13:30:00Z',
  },
  {
    id: 'person_8',
    name: 'Quinn Foster',
    department: 'Engineering',
    managerId: 'person_4',
    slackUserId: 'U008',
    riskScore: 6.2,
    riskLevel: 'warning',
    signals: ['sentiment_drift', 'after_hours'],
    lastActivity: '2024-06-17T12:45:00Z',
  },
  {
    id: 'person_9',
    name: 'Avery Brooks',
    department: 'Product',
    managerId: 'person_5',
    slackUserId: 'U009',
    riskScore: 3.8,
    riskLevel: 'watch',
    signals: ['response_drop'],
    lastActivity: '2024-06-17T11:20:00Z',
  },
  {
    id: 'person_10',
    name: 'Jordan Blake',
    department: 'Marketing',
    managerId: null,
    slackUserId: 'U010',
    riskScore: 1.2,
    riskLevel: 'normal',
    signals: [],
    lastActivity: '2024-06-17T16:00:00Z',
  },
]

export const mockAlerts: Alert[] = [
  {
    id: 'alert_1',
    personId: 'person_1',
    personName: 'Alex M.',
    severity: 'critical',
    signals: ['sentiment_drift', 'after_hours', 'channel_exclusion'],
    firedAt: '2024-06-17T14:32:00Z',
    status: 'open',
    evidenceCount: 12,
  },
  {
    id: 'alert_2',
    personId: 'person_8',
    personName: 'Quinn Foster',
    severity: 'warning',
    signals: ['sentiment_drift', 'after_hours'],
    firedAt: '2024-06-17T12:45:00Z',
    status: 'open',
    evidenceCount: 8,
  },
  {
    id: 'alert_3',
    personId: 'person_2',
    personName: 'Jordan Chen',
    severity: 'warning',
    signals: ['response_drop'],
    firedAt: '2024-06-17T10:15:00Z',
    status: 'acknowledged',
    evidenceCount: 5,
  },
]

export const mockRelationships: Relationship[] = [
  {
    actorId: 'person_1',
    targetId: 'person_4',
    interactionCount: 47,
    avgSentiment: -0.62,
    sentimentTrend: 'falling',
    riskLevel: 'critical',
    powerDelta: -1,
  },
  {
    actorId: 'person_1',
    targetId: 'person_5',
    interactionCount: 23,
    avgSentiment: -0.41,
    sentimentTrend: 'falling',
    riskLevel: 'warning',
    powerDelta: 0,
  },
  {
    actorId: 'person_1',
    targetId: 'person_8',
    interactionCount: 15,
    avgSentiment: -0.35,
    sentimentTrend: 'stable',
    riskLevel: 'warning',
    powerDelta: 1,
  },
  {
    actorId: 'person_1',
    targetId: 'person_2',
    interactionCount: 8,
    avgSentiment: -0.18,
    sentimentTrend: 'rising',
    riskLevel: 'normal',
    powerDelta: 0,
  },
]

export const mockMessages: MessageEvent[] = [
  {
    eventId: 'msg_1',
    orgId: 'org_1',
    senderId: 'person_1',
    senderName: 'Alex M.',
    recipientIds: ['person_4'],
    channel: '#general',
    channelType: 'public',
    text: "I don't know why we even bother with these meetings. Nothing ever changes anyway.",
    sentimentScore: -0.72,
    signals: ['sentiment_drift', 'channel_exclusion'],
    timestamp: '2024-06-17T14:32:00Z',
  },
  {
    eventId: 'msg_2',
    orgId: 'org_1',
    senderId: 'person_1',
    senderName: 'Alex M.',
    recipientIds: ['person_4'],
    channel: 'dm',
    channelType: 'dm',
    text: 'Can we talk about the project review? I have some concerns about how things are being handled.',
    sentimentScore: -0.41,
    signals: ['after_hours'],
    timestamp: '2024-06-17T22:15:00Z',
  },
  {
    eventId: 'msg_3',
    orgId: 'org_1',
    senderId: 'person_1',
    senderName: 'Alex M.',
    recipientIds: ['person_4'],
    channel: 'dm',
    channelType: 'dm',
    text: "Anyway, I've been thinking about my career here. The direction doesn't feel right anymore.",
    sentimentScore: -0.58,
    signals: ['after_hours', 'sentiment_drift'],
    timestamp: '2024-06-17T23:42:00Z',
  },
  {
    eventId: 'msg_4',
    orgId: 'org_1',
    senderId: 'person_1',
    senderName: 'Alex M.',
    recipientIds: ['person_5'],
    channel: '#engineering',
    channelType: 'public',
    text: 'The way this was communicated to us was pretty disappointing. No heads up beforehand.',
    sentimentScore: -0.51,
    signals: ['sentiment_drift'],
    timestamp: '2024-06-17T13:20:00Z',
  },
  {
    eventId: 'msg_5',
    orgId: 'org_1',
    senderId: 'person_1',
    senderName: 'Alex M.',
    recipientIds: ['person_8'],
    channel: 'dm',
    channelType: 'dm',
    text: 'You getting the same vibe from leadership that I am? Things feel off lately.',
    sentimentScore: -0.38,
    signals: ['after_hours'],
    timestamp: '2024-06-17T21:05:00Z',
  },
  {
    eventId: 'msg_6',
    orgId: 'org_1',
    senderId: 'person_1',
    senderName: 'Alex M.',
    recipientIds: ['person_4'],
    channel: '#random',
    channelType: 'public',
    text: 'Good work on the deploy this morning.',
    sentimentScore: 0.15,
    signals: [],
    timestamp: '2024-06-17T09:30:00Z',
  },
  {
    eventId: 'msg_7',
    orgId: 'org_1',
    senderId: 'person_1',
    senderName: 'Alex M.',
    recipientIds: ['person_2'],
    channel: '#general',
    channelType: 'public',
    text: "Not sure how we're supposed to hit the deadline with the current scope. This seems unrealistic.",
    sentimentScore: -0.44,
    signals: ['response_drop'],
    timestamp: '2024-06-17T15:45:00Z',
  },
  {
    eventId: 'msg_8',
    orgId: 'org_1',
    senderId: 'person_1',
    senderName: 'Alex M.',
    recipientIds: ['person_4', 'person_5'],
    channel: 'dm',
    channelType: 'group_dm',
    text: 'I appreciate the opportunity, but I think I need to move on. I have other options.',
    sentimentScore: -0.35,
    signals: ['after_hours', 'channel_exclusion'],
    timestamp: '2024-06-18T00:30:00Z',
  },
]

export const mockRiskScoreBreakdown: RiskScoreBreakdown = {
  sentimentDrift: 7.8,
  afterHours: 8.5,
  channelExclusion: 7.2,
  responseDrop: 3.1,
  composite: 8.1,
}

export const mockMetrics = {
  totalEmployees: 247,
  activeAlerts: 3,
  highRiskRelationships: 12,
  messagesAnalyzedToday: 5843,
}
